name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: test_name_and_price_in_cart
        type: choice
        options:
          - test_name_and_price_in_cart
          - run_all_tests

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chrome and xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run single test
        if: github.event.inputs.deployment_target == 'test_name_and_price_in_cart'
        run: xvfb-run -s "-screen 0 2560x1440x24" pytest tests/test_name_and_price_in_cart.py -s -v

      - name: Run all tests
        if: github.event.inputs.deployment_target == 'run_all_tests'
        run: xvfb-run -s "-screen 0 2560x1440x24" pytest -s -v

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots
